version: '3.4'

services:

  artists_search:
    image: ${DOCKER_REGISTRY-}artists_search
    build:
      context: .
      dockerfile: ArtistSearch.API/Dockerfile
    ports:
      - "80:80"
      - "443:443"

